title: "SDNet Demo"
description: SDNet is a neural network that can remove background noise while extending the bandwidth of speech.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
